Improves handling of `make check` dependency on python3.
See related Easel commit for more detail.

Also adds HMMER3 documentation/userguide/inclusions/Makefile to the
configure script.

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -60,7 +60,6 @@ CPPFLAGS  = @CPPFLAGS@
 AR        = @AR@ 
 RANLIB    = @RANLIB@
 INSTALL   = @INSTALL@
-PYTHON3   = @PYTHON3@
 
 # beautification magic stolen from git 
 #
@@ -127,10 +126,7 @@ tests:
 # don't need to run the Easel testsuite twice.
 #
 check:
-	@if ! test ${PYTHON3}; then\
-	    echo "No python3 found. 'make check' self tests are disabled.";\
-	    exit 1;\
-	fi
+	@command -v python3 >/dev/null 2>&1 || { echo >&2 "python3 is required for 'make check', but is not in your PATH. Aborting."; exit 1; }
 	${QUIET_SUBDIR0}${ESLDIR}              ${QUIET_SUBDIR1} tests
 	${QUIET_SUBDIR0}${SADIR}               ${QUIET_SUBDIR1} all
 	${QUIET_SUBDIR0}${HMMERDIR}            ${QUIET_SUBDIR1} tests
@@ -142,10 +138,7 @@ check:
 # devcheck: Run Infernal developer test suite (slower, but more comprehensive than 'check').
 #
 devcheck:
-	@if ! test ${PYTHON3}; then\
-	    echo "No python3 found. 'make devcheck' self tests are disabled.";\
-	    exit 1;\
-	fi
+	@command -v python3 >/dev/null 2>&1 || { echo >&2 "python3 is required for 'make devcheck', but is not in your PATH. Aborting."; exit 1; }
 	${QUIET_SUBDIR0}testsuite  ${QUIET_SUBDIR1} devcheck
 
 # pdf: compile the User Guides.
diff --git a/testsuite/Makefile.in b/testsuite/Makefile.in
--- a/testsuite/Makefile.in
+++ b/testsuite/Makefile.in
@@ -6,7 +6,6 @@ SQCLEVEL    = 1
 DEVSQCLEVEL = 2
 
 ESLDIR  = @INFERNAL_ESLDIR@
-PYTHON3 = @PYTHON3@
 
 # beautification magic stolen from git 
 #
@@ -25,20 +24,14 @@ endif
 
 
 check: 
-	@if ! test ${PYTHON3}; then\
-	    echo "No python3 found. 'make check' self tests are disabled.";\
-	    exit 1;\
-	fi
+	@command -v python3 >/dev/null 2>&1 || { echo >&2 "python3 is required for 'make check', but is not in your PATH. Aborting."; exit 1; }
 	@echo 
 	@echo Running Infernal test suite...
 	@echo
 	@${srcdir}/../${ESLDIR}/devkit/sqc ${SQCLEVEL} ${srcdir}/testsuite.sqc .. ${srcdir}/..
 
 devcheck: 
-	@if ! test ${PYTHON3}; then\
-	    echo "No python3 found. 'make devcheck' self tests are disabled.";\
-	    exit 1;\
-	fi
+	@command -v python3 >/dev/null 2>&1 || { echo >&2 "python3 is required for 'make devcheck', but is not in your PATH. Aborting."; exit 1; }
 	@echo 
 	@echo Running Infernal developer test suite...
 	@echo
